int (*dce_lkl_add_gateway)(int af,void * gwaddr);
int (*dce_lkl_add_neighbor)(int ifindex,int af,void * addr,void * mac);
int (*dce_lkl_closedir)(struct lkl_dir * dir);
int (*dce_lkl_dirfd)(struct lkl_dir * dir);
int (*dce_lkl_disk_add)(struct lkl_disk * disk);
int (*dce_lkl_disk_remove)(struct lkl_disk disk);
int (*dce_lkl_encode_dev_from_sysfs)(const char * sysfs_path,uint32_t * pdevid);
int (*dce_lkl_errdir)(struct lkl_dir * dir);
struct lkl_dir * (*dce_lkl_fdopendir)(int fd,int * err);
int (*dce_lkl_get_virtio_blkdev)(int disk_id,unsigned int part,uint32_t * pdevid);
int (*dce_lkl_if_add_gateway)(int ifindex,int af,void * gwaddr);
int (*dce_lkl_if_add_ip)(int ifindex,int af,void * addr,unsigned int netprefix_len);
int (*dce_lkl_if_add_linklocal)(int ifindex,int af,void * addr,int netprefix_len);
int (*dce_lkl_if_add_rule_from_saddr)(int ifindex,int af,void * saddr);
int (*dce_lkl_if_del_ip)(int ifindex,int af,void * addr,unsigned int netprefix_len);
int (*dce_lkl_if_down)(int ifindex);
int (*dce_lkl_if_set_ipv4)(int ifindex,unsigned int addr,unsigned int netmask_len);
int (*dce_lkl_if_set_ipv4_gateway)(int ifindex,unsigned int addr,unsigned int netmask_len,unsigned int gw_addr);
int (*dce_lkl_if_set_ipv6)(int ifindex,void * addr,unsigned int netprefix_len);
int (*dce_lkl_if_set_ipv6_gateway)(int ifindex,void * addr,unsigned int netmask_len,void * gw_addr);
int (*dce_lkl_if_set_mtu)(int ifindex,int mtu);
int (*dce_lkl_if_up)(int ifindex);
int (*dce_lkl_if_wait_ipv6_dad)(int ifindex,void * addr);
long (*dce_lkl_mount_dev)(unsigned int disk_id,unsigned int part,const char * fs_type,int flags,const char * opts,char * mnt_str,unsigned int mnt_str_len);
int (*dce_lkl_mount_fs)(char * fstype);
int (*dce_lkl_netdev_add)(struct lkl_netdev * nd,struct lkl_netdev_args * args);
struct lkl_netdev * (*dce_lkl_netdev_dpdk_create)(const char * ifname,int offload,unsigned char * mac);
void (*dce_lkl_netdev_free)(struct lkl_netdev * nd);
int (*dce_lkl_netdev_get_ifindex)(int id);
struct lkl_netdev * (*dce_lkl_netdev_macvtap_create)(const char * path,int offload);
struct lkl_netdev * (*dce_lkl_netdev_pipe_create)(const char * ifname,int offload);
struct lkl_netdev * (*dce_lkl_netdev_raw_create)(const char * ifname);
void (*dce_lkl_netdev_remove)(int id);
struct lkl_netdev * (*dce_lkl_netdev_tap_create)(const char * ifname,int offload);
struct lkl_netdev * (*dce_lkl_netdev_vde_create)(const char * switch_path);
struct lkl_dir * (*dce_lkl_opendir)(const char * path,int * err);
void (*dce_lkl_perror)(char * msg,int err);
int (*dce_lkl_qdisc_add)(int ifindex,char * root,char * type);
void (*dce_lkl_qdisc_parse_add)(int ifindex,char * entries);
struct lkl_linux_dirent64 * (*dce_lkl_readdir)(struct lkl_dir * dir);
void (*dce_lkl_register_dbg_handler)(void);
void (*dce_lkl_rewinddir)(struct lkl_dir * dir);
int (*dce_lkl_set_fd_limit)(unsigned int fd_limit);
int (*dce_lkl_set_ipv4_gateway)(unsigned int addr);
int (*dce_lkl_set_ipv6_gateway)(void * addr);
const char * (*dce_lkl_strerror)(int err);
long long (*dce_lkl_sys_lseek)(unsigned int fd,__lkl__kernel_loff_t off,unsigned int whence);
void * (*dce_lkl_sys_mmap)(void * addr,size_t length,int prot,int flags,int fd,off_t offset);
int (*dce_lkl_sysctl)(const char * path,const char * value);
int (*dce_lkl_sysctl_get)(const char *path, char *buffer, int size);
void (*dce_lkl_sysctl_parse_write)(const char * sysctls);
long (*dce_lkl_umount_dev)(unsigned int disk_id,unsigned int part,int flags,long timeout_ms);
long (*dce_lkl_umount_timeout)(char * path,int flags,long timeout_ms);
